src/Entity/Playlist.php
<?php

namespace App\Entity;

use App\Repository\PlaylistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlaylistRepository::class)]
class Playlist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'playlists')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $createdBy = null;

    /**
     * @var Collection<int, PlaylistSubscription>
     */
    #[ORM\OneToMany(targetEntity: PlaylistSubscription::class, mappedBy: 'playlist', orphanRemoval: true)]
    private Collection $playlistSubscriptions;

    /**
     * @var Collection<int, PlaylistMedia>
     */
    #[ORM\OneToMany(targetEntity: PlaylistMedia::class, mappedBy: 'playlist', orphanRemoval: true)]
    private Collection $playlistMedia;

    public function __construct()
    {
        $this->playlistSubscriptions = new ArrayCollection();
        $this->playlistMedia = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?User $createdBy): static
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * @return Collection<int, PlaylistSubscription>
     */
    public function getPlaylistSubscriptions(): Collection
    {
        return $this->playlistSubscriptions;
    }

    public function addPlaylistSubscription(PlaylistSubscription $playlistSubscription): static
    {
        if (!$this->playlistSubscriptions->contains($playlistSubscription)) {
            $this->playlistSubscriptions->add($playlistSubscription);
            $playlistSubscription->setPlaylist($this);
        }

        return $this;
    }

    public function removePlaylistSubscription(PlaylistSubscription $playlistSubscription): static
    {
        if ($this->playlistSubscriptions->removeElement($playlistSubscription)) {
            // set the owning side to null (unless already changed)
            if ($playlistSubscription->getPlaylist() === $this) {
                $playlistSubscription->setPlaylist(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PlaylistMedia>
     */
    public function getPlaylistMedia(): Collection
    {
        return $this->playlistMedia;
    }

    public function addPlaylistMedium(PlaylistMedia $playlistMedium): static
    {
        if (!$this->playlistMedia->contains($playlistMedium)) {
            $this->playlistMedia->add($playlistMedium);
            $playlistMedium->setPlaylist($this);
        }

        return $this;
    }

    public function removePlaylistMedium(PlaylistMedia $playlistMedium): static
    {
        if ($this->playlistMedia->removeElement($playlistMedium)) {
            // set the owning side to null (unless already changed)
            if ($playlistMedium->getPlaylist() === $this) {
                $playlistMedium->setPlaylist(null);
            }
        }

        return $this;
    }

    public function getAllMoviePlaylistMedia(): Collection
    {
        $result = [];

        foreach ($this->playlistMedia as $playlistMedia) {
            $media = $playlistMedia->getMedia();

            if ($media instanceof Movie) {
                $result[] = $media;
            }
        }

        return new ArrayCollection($result);
    }

    public function getAllSeriePlaylistMedia(): Collection
    {
        $result = [];

        foreach ($this->playlistMedia as $playlistMedia) {
            $media = $playlistMedia->getMedia();

            if ($media instanceof Serie) {
                $result[] = $media;
            }
        }

        return new ArrayCollection($result);
    }
}

src/Controller/Other/ListController.php
<?php

namespace App\Controller\Other;

use App\Entity\PlaylistSubscription;
use App\Repository\PlaylistRepository;
use App\Repository\PlaylistSubscriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ListController extends AbstractController
{
    #[Route(path: '/lists', name: 'show_my_list')]
    public function show(
        PlaylistRepository $playlistRepository,
        PlaylistSubscriptionRepository $playlistSubscriptionRepository,
        Request $request,
    ): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        $playlistId = $request->query->get('playlist');

        if ($playlistId) {
            $playlist = $playlistRepository->find($playlistId);
        } else {
            $playlist = null;
        }

        $playlists = $playlistRepository->findAll();
        $subscribedPlaylists = $playlistSubscriptionRepository->findBy(['subscriber' => $user]);

        return $this->render('other/lists.html.twig', [
            'playlists' => $playlists,
            'subscribedPlaylists' => $subscribedPlaylists,
            'activePlaylist' => $playlist,
        ]);
    }
}

src/Controller/Other/PhotoController.php
<?php

namespace App\Controller\Other;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class PhotoController extends AbstractController
{
    #[Route(path: '/upload', name: "upload")]
    public function upload(): Response
    {
        return $this->render('other/upload.html.twig');
    }
}

src/Controller/Other/SubscriptionController.php
<?php

namespace App\Controller\Other;

use App\Repository\SubscriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class SubscriptionController extends AbstractController
{
    #[Route(path: '/subscriptions', name: 'subscriptions')]
    public function show(
        SubscriptionRepository $subscriptionRepository
    ): Response
    {
        $subscriptions = $subscriptionRepository->findAll();

        return $this->render('other/subscriptions.html.twig', [
            'subscriptions' => $subscriptions,
        ]);
    }
}

templates/other/abonnements.html.twig
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Streemi - Abonnements</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="font-montserrat text-sm bg-white " >
<div class="flex min-h-screen  2xl:max-w-screen-2xl 2xl:mx-auto 2xl:border-x-2 2xl:border-gray-200">
    {% include 'parts/menu-left.html.twig' %}
    <main class=" flex-1 py-10  px-5 sm:px-10 ">
        <header class=" font-bold text-lg flex items-center  gap-x-3 md:hidden">
                <span class="mr-6">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7 text-gray-700" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h7" />
                      </svg>
                </span>
            <svg class="h-8 w-8 fill-red-600 shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                <path d="M10 15.5v-7c0-.41.47-.65.8-.4l4.67 3.5c.27.2.27.6 0 .8l-4.67 3.5c-.33.25-.8.01-.8-.4Zm11.96-4.45c.58 6.26-4.64 11.48-10.9 10.9 -4.43-.41-8.12-3.85-8.9-8.23 -.26-1.42-.19-2.78.12-4.04 .14-.58.76-.9 1.31-.7v0c.47.17.75.67.63 1.16 -.2.82-.27 1.7-.19 2.61 .37 4.04 3.89 7.25 7.95 7.26 4.79.01 8.61-4.21 7.94-9.12 -.51-3.7-3.66-6.62-7.39-6.86 -.83-.06-1.63.02-2.38.2 -.49.11-.99-.16-1.16-.64v0c-.2-.56.12-1.17.69-1.31 1.79-.43 3.75-.41 5.78.37 3.56 1.35 6.15 4.62 6.5 8.4ZM5.5 4C4.67 4 4 4.67 4 5.5 4 6.33 4.67 7 5.5 7 6.33 7 7 6.33 7 5.5 7 4.67 6.33 4 5.5 4Z"></path>
            </svg>
            <div class="tracking-wideflex-1">MMovie<span class="text-red-600">.</span></div>
        </header>
        <section>
            <h1 class="text-lg font-medium text-black">Nos <span class="font-bold text-red-600">abonnements</span></h1>
            <p class="text-gray-400 text-lg mt-3">Profitez de notre catalogue exclusif de films & séries à prix concurentiel.</p>
            <div class="flex items-center font-medium mt-8 bg-gray-100 border border-black/10 rounded-lg px-8 py-4">
                <svg class="h-5 w-5 fill-current opacity-50 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>information</title><path d="M13,9H11V7H13M13,17H11V11H13M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
                Votre abonnement actuel : <span class="text-red-600 font-bold ml-2">Aucun</span>
            </div>
            <ul class="mt-9 grid grid-cols-2 gap-y-5 gap-x-5">
                {% for subscription in subscriptions %}
                    {% include 'parts/subscription/subscription_card.html.twig' %}
                {% endfor %}
            </ul>
        </section>
    </main>
</div>

</body>

</html>

templates/other/lists.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes playlists{% endblock %}

{% block contenu_page %}
    <div>
        <section>
            <h1 class="font-medium text-black text-lg">Mes listes de <span class="font-bold text-red-600">films</span> et <span class="font-bold text-red-600">séries</span></h1>

            <div class="flex flex-col space-y-3 mt-9">
                <div class="relative w-full flex space-x-3 text-gray-700 font-medium">
                    <button class="flex w-1/3 text-nowrap items-center p-3 rounded-md border hover:scale-105 cursor-pointer transition hover:bg-gray-100">
                        <svg class="fill-current h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>plus-circle</title><path d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
                        Créer une liste
                    </button>
                    <button class="flex w-1/3 text-nowrap items-center p-3 rounded-md border hover:scale-105 cursor-pointer transition hover:bg-gray-100">
                        <svg class="fill-current h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>link-plus</title><path d="M7,7H11V9H7A3,3 0 0,0 4,12A3,3 0 0,0 7,15H11V17H7A5,5 0 0,1 2,12A5,5 0 0,1 7,7M17,7A5,5 0 0,1 22,12H20A3,3 0 0,0 17,9H13V7H17M8,11H16V13H8V11M17,12H19V15H22V17H19V20H17V17H14V15H17V12Z" /></svg>
                        Suivre une liste
                    </button>
                    <button class="flex w-1/3 text-nowrap items-center p-3 rounded-md border hover:scale-105 cursor-pointer transition hover:bg-gray-100">
                        <svg class="fill-current h-4 w-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>share-circle</title><path d="M12 2C6.5 2 2 6.5 2 12S6.5 22 12 22 22 17.5 22 12 17.5 2 12 2M14 16V13C10.39 13 7.81 14.43 6 17C6.72 13.33 8.94 9.73 14 9V6L19 11L14 16Z" /></svg>
                        Partager une liste
                    </button>
                </div>

                <div class="relative w-full flex text-gray-700 font-medium">
                    <select id="choosePlaylistSelect" class="appearance-none w-full bg-white border border-gray-200 px-7 py-3 rounded-md shadow transition">
                        {% for playlist in playlists %}
                            <option value="{{ playlist.id }}">#{{ loop.index }} - {{ playlist.name }} ({{ playlist.allMoviePlaylistMedia | length }} films & {{ playlist.allSeriePlaylistMedia | length }} séries)</option>
                        {% endfor %}
                        {% for subscribedPlaylist in subscribedPlaylists %}
                            <option value="{{ subscribedPlaylist.playlist.id }}">#{{ loop.index }} - {{ subscribedPlaylist.playlist.name }} ({{ subscribedPlaylist.playlist.allMoviePlaylistMedia | length }} films & {{ subscribedPlaylist.playlist.allSeriePlaylistMedia | length }} séries) - Liste de {{ subscribedPlaylist.playlist.creator.username }}</option>
                        {% endfor %}
                    </select>
                    <div class="pointer-events-none absolute right-2 inset-y-0 flex items-center px-2">
                        <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>chevron-down-circle</title><path d="M22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2A10,10 0 0,1 22,12M6,10L12,16L18,10L16.6,8.6L12,13.2L7.4,8.6L6,10Z" /></svg>
                    </div>
                </div>
            </div>
        </section>

        <section class="mt-9">
            <ul class="grid grid-cols-2 gap-y-5 sm:grid-cols-3 gap-x-5">
                {% for playlistMedia in activePlaylist.playlistMedia %}
                    {% include 'parts/movie_card_big.html.twig' %}
                {% endfor %}
            </ul>
            <button class="flex flex-col items-center mt-9 w-full">
                <div class="relative flex w-full bg-red-600 flex-row p-3 items-center justify-center rounded-lg overflow-hidden border cursor-pointer transition hover:bg-red-700 text-white">
                    <span class="font-bold mr-2">
                        <svg class="h-6 w-6" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>plus-circle</title><path d="M17,13H13V17H11V13H7V11H11V7H13V11H17M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>
                    </span>
                    <span class="capitalize font-medium text-md">Charger + de films</span>
                </div>
            </button>
        </section>
    </div>
    <script>
        const choosePlaylistSelect = document.getElementById('choosePlaylistSelect');
        choosePlaylistSelect.addEventListener('change', function() {
            window.location.href = "{{ path('show_my_list') }}?playlist=" + this.value;
        });
    </script>
{% endblock %}